export const  roadmap = [
    { no: 1 },
    { no: 2 },
    { no: 3 },
    { no: 4 },
    { no: 5 },
    { no: 10 },
    { no: 9 },
    { no: 8 },
    { no: 7 },
    { no: 6 },
    { no: 11 },
    { no: 12 },
    { no: 13 },
    { no: 14 },
    { no: 15 },
    { no: 20 },
    { no: 19 },
    { no: 18 },
    { no: 17 },
    { no: 16 },
    { no: 21 },
    { no: 22 },
    { no: 23 },
    { no: 24 },
    { no: 25 },
    { no: 30 },
    { no: 29 },
    { no: 28 },
    { no: 27 },
    { no: 26 },
    { no: 31 },
    { no: 32 },
    { no: 33 },
    { no: 34 },
    { no: 35 },
    { no: 40 },
    { no: 39 },
    { no: 38 },
    { no: 37 },
    { no: 36 },
    { no: 41 },
    { no: 42 },
    { no: 43 },
    { no: 44 }
]
export const roadMapData = [
    {
        day: 0,
        title: "No session title available",
        time: "Class schedule is not updated",
        content: "No content available",
        preread: "No preread available",
        activity: "",
        tags: "",
        task: "",
        link: ""
    },
    {
        day: 1,
        title: "Javascript - Day -1 : Introduction to Browser & web",
        time: "17/04/2023 - Monday - 10:00 AM : 1:00 PM",
        content: "Introduction to web Browser Wars DOM tree CSSOM tree, Browser internals - HTML parser, CSS parser,  JavaScript V8 engine, internals IP – MAC address – Ports & Evolution of HTTP, HTTP Methods How the Server looks at the URL Request & Response cycle",
        preread: "No preread available",
        activity: "https://docs.google.com/document/d/1QznT1zM4mI6dG0TOx5Xjs1GquMoSHO3xZ1USDnVM-w/preview",
        tags: ["javascript", "browser", "DOM"],
        task: "fs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 2,
        title: "Javascript - Day -2 : Request & Response cycle",
        time: "18/04/2023 - Tuesday - 10:00 AM : 1:00 PM",
        content: "HTML Browser view - Debugger, Inspect, Browser js vs Node js Data types Copy by value and Copy by reference Window & document object",
        preread: "No preread available",
        activity: "https://docs.google.com/document/d/1lkzy8u0rkW5v2jGvbJJrmVVLjMqN_TmmsHkL41AoIc/preview",
        tags: ["HTTP methods"],
        task: "fs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 3,
        title: "Javascript - Day -3 : JS array & objects",
        time: "19/04/2023 - Wednesday - 10:00 AM : 1:00 PM",
        content: "Introduction to Array, Array and JSON iteration, XMLHTTPRequest, Hoisting & scope",
        preread: "No preread available",
        activity: "https://docs.google.com/document/d/1cNDeT0CKJwqYDeSIlmJVhx_t4AFvR_0Ypa1cp2rhJk/edit?usp=sharing",
        tags: ["array", "JSON", "objects"],
        task: "fs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 4,
        title: "JavaScript - Day -4: Functions",
        time: "20/04/2023 - Thursday - 10:00 AM : 1:00 PM",
        content: "Introduction to functions function & return keyword types of function",
        preread: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions",
        activity: "https://docs.google.com/document/d/1TPk3wqxDi64WV-6hJOkYEzBaAYxNvZ4T9hRJGgvFjw/edit",
        tags: ["hoisting", "scope-block", "functions"],
        task: "fs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 5,
        title: "JavaScript - Day -5: ES5 vs ES6",
        time: "21/04/2023 - Friday - 10:00 AM : 12:00 PM",
        content: "var vs let vs const, block scoping, spread & rest operators, array & object destructure, Object property shorthand, Template literals, Arrow functions",
        preread: "https://aravishack.medium.com/es6-features-a-walk-through-1ffd8eb82f6",
        activity: "https://docs.google.com/document/d/1EIpyPItk5xMOQluXm_cPD4KTI9AnkyqDlO26pbG4a8/edit",
        tags: ["es5", "es6", "arrow functions", "array destructure"],
        task: "fs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 6,
        title: "JavaScript - Day -6: OOP in JS",
        time: "21/04/2023 - Friday - 1:00 PM : 3:00 PM",
        content: "Understanding the basics of prototype, What is classes in js?, consntructor, need of setters/getters, use of this key word in classes",
        preread: "No preread available",
        activity: "https://docs.google.com/document/d/1ILi6J1s3tSv8xnXImIuW5jD652BXNHNLNa0ErmRsRk/edit?usp=sharing",
        tags: ["this keyword", "OOPS"],
        task: "fs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 7,
        title: "JavaScript - Day -7: Array methods",
        time: "24/04/2023 - Monday - 6:30 PM : 9:30 PM",
        content: "Map, Reduce,  Filter, Other array methods practice in session",
        preread: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
        activity: "https://docs.google.com/document/d/12wAX28odaaCy4IWdlXQQ3LOrBB3UXLsMD99X1Ve1Uc/edit?usp=sharing",
        tags: ["arrow functions", "array methods"],
        task: "fs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 8,
        title: "HTML- Day -1 : HTML",
        time: "04/05/2023 - Thursday - 6:30 PM : 9:30 PM",
        content: "What is HTML & Why to use?, Basic Tags, HTML vs HTML5, div vs section vs article, div vs span, inline vs block elements, HTML Forms, Input elements and attributes, Form submit, Session Practice task URL: https://github.com/rvsp/HTML-CSS/blob/master/Mini-tasks/001-HTML.md",
        preread: "https://developer.mozilla.org/en-US/docs/Web/HTML,https://www.w3schools.com/html/, https://html.spec.whatwg.org/multipage/",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 9,
        title: "HTML & CSS- Day -2 : HTML & CSS",
        time: "09/05/2023 - Tuesday - 6:30 PM : 9:30 PM",
        content: "What is css?, ways to use css, property & value, class vs id, use of important, display property: inline, block",
        preread: " https://www.w3schools.com/html/default.asp, https://github.com/rvsp/html-CSS/",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 10,
        title: "HTML & CSS- Day -3 : HTML & CSS",
        time: "10/05/2023 - Wednesday - 6:30 PM : 9:30 PM",
        content: "Intro to pseudo-classes (link,visited,hover,active), box model: padding,margin,border, Grid, Flex - display, direction, wrap, flex-flow, justify-content, align-content, position property: fixed,static,relative,absolute,sticky, parent inherit, gradient",
        preread: "https://rvsp.github.io/CSS/, https://web.dev/learn/css/, https://www.w3schools.com/css/, https://css-tricks.com/, https://github.com/html-CSS/",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 11,
        title: "HTML & CSS- Day -4 : HTML & CSS",
        time: "12/05/2023 - Friday - 6:30 PM : 9:30 PM",
        content: "overflow - hidden, scroll, auto, visible, dropbox, measurements, fonts, icons, media query",
        preread: "https://rvsp.github.io/CSS/, https://web.dev/learn/css/, https://www.w3schools.com/css/, https://css-tricks.com/, https://github.com/html-CSS",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 12,
        title: "HTML & CSS- Day -5 : Responsive web design",
        time: "16/05/2023 - Tuesday - 6:30 PM : 9:30 PM",
        content: "What is RWD?, What is mobile first approach?, Bootstrap, - How to setup bootstrap?, - What is the layout?, - what is container, container-fluid & container with breakpoints?, - What is a grid in bootstrap?, - what is column prefix & it's use and maximum columns for a row?, - how to do nested columns, column ordering?",
        preread: "https://getbootstrap.com/docs/4.6/getting-started/introduction/",
        activity: "From the below Title you can pick any two and complete them with responsive design. For your reference visit this URL https://github.com/HTML-CSS/tree/master/Tasks",
        tags: ["bootstrap", "RWD"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"

    },
    {
        day: 13,
        title: "DOM- Day -1 : DOM Intor",
        time: "17/05/2023 - Wednesday - 6:30 PM : 9:30 PM",
        content: "What is DOM?, createElement, setAttribute, getElementById, querySelector vs querySelectorAll, innerHTML vs innerText, appendChild vs append",
        preread: "https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 14,
        title: "DOM- Day -2 : Document vs Window",
        time: "22/05/2023 - Monday - 6:30 PM : 9:30 PM",
        content: "Window - Common Util functions, setTimeout vs setInterval , prompt, Alert, confirm , working with events",
        preread: "https://stackoverflow.com/questions/9895202/what-is-the-difference-between-window-screen-and-document-in-javascript",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 15,
        title: "DOM- Day -3 : Recap of Topics",
        time: "23/05/2023 - Tuesday - 6:30 PM : 9:30 PM",
        content: "recap of DOM topics, Mandatory session practice task, https://github.com/rvsp/HTML-CSS/blob/master/Mini-tasks/003-JS-DOM.md",
        preread: "No preread available",
        activity: "Pagination: https://docs.google.com/document/d/1O8yVCwB_aY5rZK1_mNkZ9GeYJLeom_dYmcVN3Mb2ws/edit , HTML-Forms: https://docs.google.com/document/d/1I8qIE7_ri5Q_1QqkxJ7rdlRmGnWWW7zCa7BXwAi8hI/edit , Calculator: https://docs.google.com/document/d/1VyZJG0KZAoZEs3h_lpP65XPekqsbFp8bouOZSWsOTc/edit",
        tags: ["DOM", "html", "css"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 16,
        title: "Pre-Placement Session",
        time: "25/05/2023 - Thursday - 2:30 PM : 4:00 PM",
        content: "Mandatory session on placement readiness  factors",
        preread: "No preread available",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 17,
        title: "Async programming- Day -1 : Callback",
        time: "29/05/2023 - Monday - 8:00 AM : 11:00 AM",
        content: "Callback, What's the callback? - callstack,webapi, eventloop, queue, Use & the purpose of the callback , Pain of callback, Session reference  - http://latentflip.com/loupe/",
        preread: "https://www.freecodecamp.org/news/javascript-callback-functions-what-are-callbacks-in-js-and-how-to-use-them/",
        activity: "Callback Hell Task: https://docs.google.com/document/d/1K6jTPmqWvzoRAm2t-GlOAxKmMRsLt5zaCsdcH_3LM/edit",
        tags: ["callbacks", "callback hell", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 18,
        title: "Async programming- Day -2 : Promise",
        time: "29/05/2023 - Monday - 6:30 PM : 9:30 PM",
        content: "Promise, - What is promise?, - Promise States, - Promise chain, - promise.all(), - Use of fetch() & then()",
        preread: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
        activity: "Rest countries task https://docs.google.com/document/d/1s5jhTeSff2rHKbC5VQjao4Jbu257dxubwEKusoA9A/edit",
        tags: ["promise", "fetch-api"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"

    },
    {
        day: 19,
        title: "Async programming- Day -3 : Fetch-api",
        time: "30/05/2023 - Tuesday - 6:30 PM : 9:00 PM",
        content: "Promise chaining, Async/Await with error handling",
        preread: "No preread available",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 20,
        title: "Async programming- Day -4 : Promise fetch - request info & request init",
        time: "31/05/2023 - Wednesday - 6:30 PM : 9:30 PM",
        content: "Implementing CRUD with HTML, CSS JavaScript",
        preread: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 21,
        title: "Async programming- Day -5 : Recap of topics",
        time: "01/06/2023 - Thursday - 6:30 PM : 9:30 PM",
        content: "Recap of callback, Pormise Topics",
        preread: "No preread available",
        activity: "https://docs.google.com/document/d/1wa9laCdb__QIty4ZAre2-uYmHeq4xinhKpwjty8UI/preview",
        tags: ["promise", "fetch-api", "async-await", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 22,
        title: "React - Day 1: ES5 vs ES6",
        time: "08/06/2023 - Thursday - 6:30 PM : 9:30 PM",
        content: "ES5 vs Es6, Scoping - var vs let vs const, arrow functions, use of this keyword(lexical scoping), template literals, spred & rest prarameter, array & object destructure ,property shorthand , module import & export , Class in Javascript",
        preread: "http://es6-features.org/, https://developer.mozilla.org/en-       /US/docs/Web/JavaScript/Reference        /Operators/Destructuring_assignment",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 23,
        title: "React- Day -2 : React",
        time: "09/06/2023 - Friday - 6:30 PM : 9:30 PM",
        content: "Why react, Setup react project, Undetstanding JSX, Components (simple HTML layout to reusable react,  components), Understanding the components, Passing data through props        Deploying react to netlify",
        preread: "https://reactjs.org/",
        activity: "https://docs.google.com/document/d/11URBvZUsXT4Sr3YtCuv-5gcOkOmX976h-QKcXbWqs/edit",
        tags: ["react", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 24,
        title: "React- Day -3 : React hooks & states",
        time: "13/06/2023 - Tuesday - 6:30 PM : 9:30 PM",
        content: "Working with array lists, Usage of keys, Conditional rendering, Handling Events, Props vs state",
        preread: "https://reactjs.org/docs/hooks-overview.html,        https://reactjs.org/docs/hooks-rules.html",
        activity: "Task – * The rating according to value given * Disable add to cart button when added to card * Remove item from cart & enable add to cart https://startbootstrap.com/previews/homepage",
        tags: ["react", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 25,
        title: "React- Day -4 : React components",
        time: "14/06/2023 - Wednesday - 10:00 AM : 1:00 PM",
        content: "Components - In depth, Component life cycle ,    Stateful and stateless components, Reusable components, Passing dynamic data to component, Introduction to Hook",
        preread: "https://www.npmjs.com/package/react-router-dom",
        activity: "Task - https://startbootstrap.com/previews/admin-2 value from component need to show to other component",
        tags: ["react", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 26,
        title: "React- Day -5 : react hooks",
        time: "14/06/2023 - Wednesday - 6:30 PM : 9:30 PM",
        content: "What is hook?, Lifecycle of Hook, useState, useEffect, Props drilling, Passing data from child to parent component",
        preread: "https://www.npmjs.com/package/react-router-dom",
        activity: "Design an UI to implement the CRUD // CRUD - Create,Read,Update,Delete // Dashboard // List Users - /users // Create User - /create-user // Edit User - /edit-user/:id // profile - /profile/:id // edit-profile – /edit-profile/:id",
        tags: ["react", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 27,
        title: "React- Day -6 : react router",
        time: "16/06/2023 - Friday - 6:30 PM : 9:30 PM",
        content: "react-router-dom, BrouserRouter, Switch, Link, Route, url params",
        preread: "session task on admin dashboard, https://startbootstrap.com/previews/sb-admin-2",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 28,
        title: "React- Day -7 : react session practice",
        time: "20/06/2023 - Tuesday - 6:30 PM : 9:30 PM",
        content: "Session-based Hands-on practice Task with any Admin Dashboard",
        preread: "No preread available",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 29,
        title: "React- Day -8 : Context API",
        time: "21/06/2023 - Wednesday - 10:00 AM : 12:00 PM",
        content: "Context-API, What is context, provide, createContext, Avoid props drilling, Session task – profile name changes",
        preread: "https://reactjs.org/docs/context.html, https://reactjs.org/docs/hooks-reference.html#usestate",
        activity: "Task - same task OF ADMIN DASHBOARD TO IMPLEMENT THE CRUD WITH STUDENT & TEACHER MANAGEMENT",
        tags: ["react", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 30,
        title: "React- Day -9 : Hook-useRef, useReducer",
        time: "22/06/2023 - Thursday - 6:30 PM : 9:30 PM",
        content: "useRef, useReducer, Front end game demonstration - hangman / tictactoe / tile match",
        preread: "https://www.npmjs.com/package/axios",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 31,
        title: "React- Day -10 : react with CRUD",
        time: "23/06/2023 - Friday - 6:30 PM : 10:30 PM",
        content: "Playing around with API, fetch() or axios        Implementing simple CRUD",
        preread: "https://www.npmjs.com/package/axios",
        activity: "Task - same task OF ADMIN DASHBOARD TO IMPLEMENT THE CRUD WITH STUDENT & TEACHER MANAGEMENT",
        tags: ["react", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 32,
        title: "React- Day -11 : react practice",
        time: "26/06/2023 - Monday - 6:30 PM : 9:30 PM",
        content: "Completed recap by implementing any Front end game/CRUD to understand the importance of hooks, ex:- hangman / tictactoe / tile match",
        preread: "https://www.npmjs.com/package/formik",
        activity: "Task - Implement CRUD operation with different UI of admin dashboard for Library mangement and use formik for all form validations ",
        tags: ["react", "frontend"],
        task: "fe",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 33,
        title: "React- Day -12 : react redux",
        time: "28/06/2023 - Wednesday - 8:00 AM : 10:00 AM",
        content: "Intro to Redux - to understand the state management with react application",
        preread: "No preread available",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 34,
        title: "Redux Day 2",
        time: "28/06/2023 - Wednesday - 6:30 PM : 9:30 PM",
        content: "Redux day",
        preread: "No preread available",
        activity: "",
        tags: "",
        task: "",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 35,
        title: "Database - MySQL",
        time: "03/07/2023 - Monday - 6:30 PM : 9:30 PM",
        content: "Introduction to database, what is MySQL?, intro to MySQL engines, basic queries - create db, table, insert, update, alter, select - where clause, distinct, group by, order by, offset, limit",
        preread: "https://dev.mysql.com/doc/",
        activity: "IMDB Design a DB for IMDB 1. Movie should have multiple media(Video or Image) 2. Movie can belongs to multiple Genre 3. Movie can have multiple reviews and Review can belongs to a user 4. Artist can have multiple skills 5. Artist can perform multiple role in a single film",
        tags: ["MySQL", "database"],
        task: "bs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 36,
        title: "Database - MySQL",
        time: "05/07/2023 - Wednesday - 6:30 PM : 9:30 PM",
        content: "normalization, select queries, joins, DB model design, Intro to Mongodb & installation of mongodb",
        preread: "https://dev.mysql.com/doc/",
        activity: "Complete SQL Bolt, And submit the screenshots",
        tags: ["MySQL", "database"],
        task: "bs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 37,
        title: "Database - MongoDB",
        time: "06/07/2023 - Thursday - 6:30 PM : 9:30 PM",
        content: "intro to mongodb, why mongodb?, what is document?, what is collection?, Mongodb vs MySQL, installation of mongodb, creation of database, collections, documents, find - query & projection",
        preread: "https://docs.mongodb.com/manual/",
        activity: "https://github.com/database/mongodb",
        tags: ["mongodb", "database"],
        task: "bs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 38,
        title: "MongoDB",
        time: "07/07/2023 - Friday - 6:30 PM : 9:30 PM",
        content: "use of operators in find(), basic cursor methods - map, toArray, pretty, forEach, limit, count, sort, Aggregation",
        preread: "https://docs.mongodb.com/manual/",
        activity: "https://github.com/rvsp/database/blob/master/mongodb/day/database-design-zen-class.txt",
        tags: ["mongodb", "database"],
        task: "bs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    }, {
        day: 39,
        title: "Nodejs- Day -1 : Nodejs",
        time: "10/07/2023 - Monday - 6:30 PM : 9:30 PM",
        content: "What is nodejs?, Npm packages, - In build, - Third party, - Custom",
        preread: "https://nodejs.org/",
        activity: "Nodejs file system Task https://docs.google.com/document/d/1c_u6aHv7AQHse45GGcrCRe78liwv90S5aHwBR7tBP0/edit",
        tags: ["nodejs", "backend"],
        task: "bs",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 40,
        title: "Nodejs- Day -2 : Nodejs & Expressjs",
        time: "11/07/2023 - Tuesday - 6:30 PM : 9:30 PM",
        content: "What is express, API methods - GET, POST, PUT, DELETE, Request & response objects, Url  &  Query parameters",
        preread: "https://expressjs.com/",
        activity: "Nodejs hall booking api task https://docs.google.com/documnt/d/1rPQ2LbHtMZajA_GIZfR-Ko2MFueoT82AmfHTK9V-hM/edit",
        tags: ["nodejs", "backend"],
        task: "be",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 41,
        title: "Nodejs- Day -3 : Node & mongo DB connectivity",
        time: "12/07/2023 - Wednesday - 6:30 PM : 9:30 PM",
        content: "Connection to MongoDB(local & atlas), simultenously frontend + backend connectivity",
        preread: "No preread available",
        activity: "https://docs.google.com/document/d/1sxHk2QDyK_vjlbwWPklyTXDHHOENKqj-IHS2yNSaHQ/edit?authuser=1",
        tags: ["nodejs", "backend"],
        task: "be",
        link: "https://meet.google.com/cvn-fzsd-toe"
    }, {
        day: 42,
        title: "Nodejs- Day -4 : Nodejs deployment",
        time: "13/07/2023 - Thursday - 6:30 PM : 9:30 PM",
        content: "dotenv, Deployment, simultenously frontend + backend connectivity",
        preread: "https://www.npmjs.com/package/dotenv",
        activity: "Task - Deployment practice",
        tags: ["nodejs", "backend"],
        task: "fb",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 43,
        title: "Nodejs- Day -5 : Authentication",
        time: "17/07/2023 - Monday - 6:30 PM : 9:30 PM",
        content: "Authentication, bcrypt, simultaneously frontend + backend connectivity",
        preread: "https://www.npmjs.com/package/bcrypt",
        activity: "Task - https://docs.google.com/document/d/1I7zwdM77E3JwSXtgp2pVKgcAqPBHOwczishsKak-Qk/edit",
        tags: ["nodejs", "backend"],
        task: "fb",
        link: "https://meet.google.com/cvn-fzsd-toe"
    },
    {
        day: 44,
        title: "Nodejs- Day -6 : JWT",
        time: "18/07/2023 - Tuesday - 6:30 PM : 9:30 PM",
        content: "JWT, custom middleware, authorization, simultaneously frontend + backend connectivity",
        preread: "https://www.npmjs.com/package/jsonwebtoken",
        activity: "https://docs.google.com/document/d/1nD7fzgzw5UmFSpnHK2FVadnp4y7EaND26_AqkZzSTw/edit?authuser=1",
        tags: ["nodejs", "backend"],
        task: "fb",
        link: "https://meet.google.com/cvn-fzsd-toe"
    }
];
